[package]
name = "atcoder_solver_abc174f"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

addition = { path = "../../../crates/algebra/binary_operation/addition" }
prelude = { path = "../../../crates/prelude" }
binary_indexed_tree = { path = "../../../crates/data_structure/binary_indexed_tree" }
range_traits = { path = "../../../crates/range_traits" }

[[bin]]
name = "atcoder_solver_abc174f"
path = "main.rs"
