[package]
name = "library_checker_solver_cycle_detection_undirected"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

adjacency_list = { path = "../../../crates/graph/adjacency_list" }
find_cycle = { path = "../../../crates/graph/find_cycle" }

[[bin]]
name = "library_checker_solver_cycle_detection_undirected"
path = "main.rs"
