[package]
name = "greatest_common_divisor"
version = "0.1.0"
edition = "2018"

[dependencies]
rust_lib_for_comp = { path = "../../rust_lib_for_comp" }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "binary-gcd"
path = "./bench_binary_gcd.rs"
harness = false

[lib]
path = "lib.rs"
