[package]
name = "rolling_hash"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
mod_int_64bit = { path = "../../algebra/mod_int/mod_int_64bit" }
xor_shift = { path = "../../algo/xor_shift" }
algebra = { path = "../../algebra" }

[lib]
path = "lib.rs"
