[package]
name = "aoj_solver_intersection_of_circles"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

circle = { path = "../../../crates/geometry/circle" }

[[bin]]
name = "aoj_solver_intersection_of_circles"
path = "main.rs"
