[package]
name = "lowest_common_ancestor"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../../prelude" }
graph = { path = "../../../graph" }
euler_tour = { path = "../euler_tour" }
minimization = { path = "../../../algebra/binary_operation/minimization" }
sparse_table = { path = "../../../data_structure/sparse_table" }
int_with_index = { path = "../../../element/int_with_index" }
range_traits = { path = "../../../range_traits" }

[dev-dependencies] 
adjacency_list = { path = "../../../graph/adjacency_list" }

[lib]
path = "lib.rs"