[package]
name = "warshall_floyd"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
graph = { path = "../../graph" }
algebra = { path = "../../algebra" }
min_max_macro = { path = "../../util/min_max_macro" }

[lib]
path = "lib.rs"
