[workspace]
members = [
    'crates/algebra',
    'crates/algebra/binary_operation/addition',
    'crates/algebra/binary_operation/bit_or_operation',
    'crates/algebra/binary_operation/bit_xor_operation',
    'crates/algebra/binary_operation/greatest_common_divisor',
    'crates/algebra/binary_operation/maximization',
    'crates/algebra/binary_operation/minimization',
    'crates/algebra/binary_operation/multiplication',
    'crates/algebra/binary_operation/overwrite_operation',
    'crates/algebra/chinese_remainder_theorem',
    'crates/algebra/complex_number',
    'crates/algebra/lucas_theorem',
    'crates/algebra/matrix',
    'crates/algebra/miller_rabin',
    'crates/algebra/mod_int',
    'crates/algebra/mod_pow',
    'crates/algebra/mod_val_table',
    'crates/algebra/montgomery_multiplication_64',
    'crates/algebra/pollard_rho',
    'crates/algebra/sieve_of_erathosthenes',
    'crates/algebra/xor_basis',
    'crates/algo/baby_step_giant_step',
    'crates/algo/binary_search',
    'crates/algo/boyer_moore_majority_vote_algorithm',
    'crates/algo/chars_compress',
    'crates/algo/compress',
    'crates/algo/fxhasher',
    'crates/algo/int_to_digits',
    'crates/algo/rock_paper_scissors',
    'crates/algo/slice_bounds',
    'crates/algo/sqrt',
    'crates/algo/union_of_ranges',
    'crates/algo/xor_shift',
    'crates/convolution/bitwise_convolution',
    'crates/convolution/fast_fourier_transform',
    'crates/data_structure/binary_indexed_tree',
    'crates/data_structure/binary_indexed_tree_2d',
    'crates/data_structure/binary_search_tree',
    'crates/data_structure/binary_trie',
    'crates/data_structure/bit_set',
    'crates/data_structure/bit_matrix',
    'crates/data_structure/complete_64_part_tree',
    'crates/data_structure/cumulative_sum',
    'crates/data_structure/disjoint_sparse_table',
    'crates/data_structure/dynamic_li_chao_tree',
    'crates/data_structure/dynamic_segment_tree',
    'crates/data_structure/extend_map',
    'crates/data_structure/implicit_treap',
    'crates/data_structure/lazy_segment_tree',
    'crates/data_structure/partially_persistent_union_find',
    'crates/data_structure/priority_sum',
    'crates/data_structure/segment_tree',
    'crates/data_structure/sparse_table',
    'crates/data_structure/succinct_indexable_dictionaries',
    'crates/data_structure/treap',
    'crates/data_structure/union_find',
    'crates/data_structure/wavelet_matrix',
    'crates/data_structure/weighted_union_find',
    'crates/dynamic_programming/rerooting_dp',
    'crates/element/float_value',
    'crates/element/int_with_index',
    'crates/element/sequence',
    'crates/element/section',
    'crates/element/sum_and_prefix_max',
    'crates/enumerator/all_combination',
    'crates/enumerator/bit_combination',
    'crates/enumerator/next_permutation',
    'crates/enumerator/split_of_natural_number',
    'crates/enumerator/subset',
    'crates/geometry/circle',
    'crates/geometry/closest_pair',
    'crates/geometry/convex_hull',
    'crates/geometry/floor_sum',
    'crates/geometry/plane_float',
    'crates/geometry/plane_int',
    'crates/graph',
    'crates/graph/adjacency_list',
    'crates/graph/adjacency_matrix',
    'crates/graph/bellman_ford',
    'crates/graph/bipartite_graph',
    'crates/graph/dijkstra',
    'crates/graph/directed_acyclic_graph',
    'crates/graph/find_cycle',
    'crates/graph/grid',
    'crates/graph/kruskal',
    'crates/graph/prim',
    'crates/graph/retrograde_analysis',
    'crates/graph/strongly_connected_components',
    'crates/graph/tree',
    'crates/graph/tree/euler_tour',
    'crates/graph/tree/heavy_light_decomposition',
    'crates/graph/tree/lowest_common_ancestor',
    'crates/graph/undirected_unweighted_simple_graph',
    'crates/graph/warshall_floyd',
    'crates/flow/dinic',
    'crates/flow/flow_vertices',
    'crates/flow/primal_dual',
    'crates/prelude',
    'crates/print/vec2d',
    'crates/range_traits',
    'crates/string/knuth_morris_pratt',
    'crates/string/lexicographically_combine',
    'crates/string/longest_common_prefix_array',
    'crates/string/longest_increasing_subsequence',
    'crates/string/manachar',
    'crates/string/morris_pratt',
    'crates/string/rolling_hash',
    'crates/string/run_length_encoding',
    'crates/string/suffix_array',
    'crates/string/trie',
    'crates/string/z_algorithm',
    'crates/typical_problems/highly_composite_number',
    'crates/typical_problems/range_query/static_range_set_query',
    'crates/typical_problems/range_query/static_range_frequency',
    'crates/util/dbg_macro',
    'crates/util/io_debug',
    'crates/util/io_util',
    'crates/util/min_max_macro',
    'crates/util/solver',
    'crates/util/string_util',
    'crates/util/time_keeper',
    'solvers/aoj',
    'solvers/library_checker',
    'verifications/aoj',
    'verifications/library_checker',
]

[profile.release]
lto = true
panic = 'abort'
overflow-checks = true

[profile.test]
opt-level = 3
