[package]
name = "rust_lib_for_comp"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"
rust-version = "1.42"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-snippet = "0.6"

[dev-dependencies]

# RNG 疑似乱数生成器 (randファミリー)
rand = { version = "=0.7.3", features = ["small_rng"] }
getrandom = "=0.1.14"
rand_chacha = "=0.2.1"
rand_core = "=0.5.1"
rand_hc = "=0.2.0"
rand_pcg = "=0.2.1"
# 乱数分布
rand_distr = "=0.2.2"

# イテレータの強化
itertools = "=0.8.2"
itertools-num = "=0.1.3"

criterion = "=0.4.0"

[profile.release]
lto = true
panic = 'abort'
overflow-checks = true

[profile.test]
opt-level = 3

[[bench]]
name = "benchmark"
harness = false

[[example]]
name = "hello-world"
path = "examples/hello_world.rs"

[[example]]
name = "rmq-disjoint-sparse-table"
path = "examples/rmq_disjoint_sparse_table.rs"