[workspace]
members = ['library', 'verifications/*', 'benches/*']
exclude = [
    'verifications/aoj',
    'verifications/atcoder',
    'verifications/library_checker',
    'verifications/yukicoder',
]
resolver = "2"

[profile.release]
lto = true
panic = 'abort'
overflow-checks = true

[profile.test]
opt-level = 3
