[package]
name = "rust_lib_for_comp"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"
rust-version = "1.42"

[workspace]
members = [
    'crates/algebra',
    'crates/algebra/binary_operation/addition',
    'crates/algebra/binary_operation/bit_or_operation',
    'crates/algebra/binary_operation/bit_xor_operation',
    'crates/algebra/binary_operation/greatest_common_divisor',
    'crates/algebra/binary_operation/maximization',
    'crates/algebra/binary_operation/minimization',
    'crates/algebra/binary_operation/multiplication',
    'crates/algebra/binary_operation/overwrite_operation',
    'crates/algebra/chinese_remainder_theorem',
    'crates/algebra/complex_number',
    'crates/algebra/lucas_theorem',
    'crates/algebra/matrix',
    'crates/algebra/mod_int',
    'crates/algebra/mod_pow',
    'crates/algebra/mod_val_table',
    'crates/algo/fxhasher',
    'crates/data_structure/segment_tree',
    'crates/data_structure/disjoint_sparse_table',
    'crates/prelude',
    'crates/range_traits',
    'crates/io_util',
    'crates/solver',
    'crates/dbg_macro',
]

[dependencies]
cargo-snippet = "0.6"

[dev-dependencies]

# RNG 疑似乱数生成器 (randファミリー)
rand = { version = "=0.7.3", features = ["small_rng"] }
getrandom = "=0.1.14"
rand_chacha = "=0.2.1"
rand_core = "=0.5.1"
rand_hc = "=0.2.0"
rand_pcg = "=0.2.1"
# 乱数分布
rand_distr = "=0.2.2"

# イテレータの強化
itertools = "=0.8.2"
itertools-num = "=0.1.3"

criterion = "=0.4.0"

[profile.release]
lto = true
panic = 'abort'
overflow-checks = true

[profile.test]
opt-level = 3

[[bench]]
name = "benchmark"
harness = false

[[example]]
name = "hello-world"
path = "examples/hello_world.rs"
