[workspace]
members = [
    'crates/algebra',
    'crates/algebra/binary_operation/addition',
    'crates/algebra/binary_operation/bit_or_operation',
    'crates/algebra/binary_operation/bit_xor_operation',
    'crates/algebra/binary_operation/greatest_common_divisor',
    'crates/algebra/binary_operation/maximization',
    'crates/algebra/binary_operation/minimization',
    'crates/algebra/binary_operation/multiplication',
    'crates/algebra/binary_operation/overwrite_operation',
    'crates/algebra/chinese_remainder_theorem',
    'crates/algebra/complex_number',
    'crates/algebra/const_mod_val_table',
    'crates/algebra/lucas_theorem',
    'crates/algebra/matrix',
    'crates/algebra/miller_rabin',
    'crates/algebra/mod_int',
    'crates/algebra/mod_pow',
    'crates/algebra/mod_val_table',
    'crates/algebra/montgomery_multiplication_64',
    'crates/algebra/pollard_rho',
    'crates/algebra/sieve_of_erathosthenes',
    'crates/algebra/xor_basis',
    'crates/algo/baby_step_giant_step',
    'crates/algo/binary_search',
    'crates/algo/boyer_moore_majority_vote_algorithm',
    'crates/algo/chars_compress',
    'crates/algo/compress',
    'crates/algo/fxhasher',
    'crates/algo/int_to_digits',
    'crates/algo/rock_paper_scissors',
    'crates/algo/slice_bounds',
    'crates/algo/sqrt',
    'crates/algo/union_of_ranges',
    'crates/algo/xor_shift',
    'crates/convolution/bitwise_convolution',
    'crates/convolution/fast_fourier_transform',
    'crates/data_structure/binary_indexed_tree',
    'crates/data_structure/binary_indexed_tree_2d',
    'crates/data_structure/binary_search_tree',
    'crates/data_structure/binary_trie',
    'crates/data_structure/bit_set',
    'crates/data_structure/bit_matrix',
    'crates/data_structure/complete_64_part_tree',
    'crates/data_structure/cumulative_sum',
    'crates/data_structure/disjoint_sparse_table',
    'crates/data_structure/dynamic_li_chao_tree',
    'crates/data_structure/dynamic_segment_tree',
    'crates/data_structure/extend_map',
    'crates/data_structure/implicit_treap',
    'crates/data_structure/lazy_segment_tree',
    'crates/data_structure/partially_persistent_union_find',
    'crates/data_structure/priority_sum',
    'crates/data_structure/segment_tree',
    'crates/data_structure/sparse_table',
    'crates/data_structure/succinct_indexable_dictionaries',
    'crates/data_structure/treap',
    'crates/data_structure/union_find',
    'crates/data_structure/wavelet_matrix',
    'crates/data_structure/weighted_union_find',
    'crates/dynamic_programming/rerooting_dp',
    'crates/element/float_value',
    'crates/element/int_with_index',
    'crates/element/sequence',
    'crates/element/section',
    'crates/element/sum_and_prefix_max',
    'crates/enumerator/all_combination',
    'crates/enumerator/bit_combination',
    'crates/enumerator/next_permutation',
    'crates/enumerator/split_of_natural_number',
    'crates/enumerator/subset',
    'crates/geometry/circle',
    'crates/geometry/closest_pair',
    'crates/geometry/convex_hull',
    'crates/geometry/floor_sum',
    'crates/geometry/plane_float',
    'crates/geometry/plane_int',
    'crates/graph',
    'crates/graph/adjacency_list',
    'crates/graph/adjacency_matrix',
    'crates/graph/bellman_ford',
    'crates/graph/bipartite_graph',
    'crates/graph/dijkstra',
    'crates/graph/directed_acyclic_graph',
    'crates/graph/find_cycle',
    'crates/graph/grid',
    'crates/graph/kruskal',
    'crates/graph/prim',
    'crates/graph/retrograde_analysis',
    'crates/graph/strongly_connected_components',
    'crates/graph/tree/unweighted_tree',
    'crates/graph/tree/euler_tour',
    'crates/graph/tree/heavy_light_decomposition',
    'crates/graph/tree/lowest_common_ancestor',
    'crates/graph/undirected_unweighted_simple_graph',
    'crates/graph/warshall_floyd',
    'crates/flow/dinic',
    'crates/flow/flow_vertices',
    'crates/flow/primal_dual',
    'crates/prelude',
    'crates/print/vec2d',
    'crates/range_traits',
    'crates/string/knuth_morris_pratt',
    'crates/string/lexicographically_combine',
    'crates/string/longest_common_prefix_array',
    'crates/string/longest_increasing_subsequence',
    'crates/string/manachar',
    'crates/string/morris_pratt',
    'crates/string/rolling_hash',
    'crates/string/run_length_encoding',
    'crates/string/suffix_array',
    'crates/string/trie',
    'crates/string/z_algorithm',
    'crates/typical_problems/highly_composite_number',
    'crates/typical_problems/range_query/static_range_set_query',
    'crates/util/dbg_macro',
    'crates/util/io_debug',
    'crates/util/io_util',
    'crates/util/min_max_macro',
    'crates/util/solver',
    'crates/util/string_util',
    'crates/util/time_keeper',
    'solvers/atcoder',
    'verifications/aoj/area',
    'verifications/aoj/awkward_lights',
    'verifications/aoj/chopsticks',
    'verifications/aoj/circumscribed_circle_of_a_triangle',
    'verifications/aoj/closest_pair',
    'verifications/aoj/convex_cut',
    'verifications/aoj/convex_hull',
    'verifications/aoj/counter_clockwise',
    'verifications/aoj/cross_point',
    'verifications/aoj/cross_points_of_a_circle_and_a_line',
    'verifications/aoj/cross_points_of_circles',
    'verifications/aoj/dag_reachability',
    'verifications/aoj/diameter_of_a_convex_polygons',
    'verifications/aoj/distance',
    'verifications/aoj/incircle_of_a_triangle',
    'verifications/aoj/intersection_of_circles',
    'verifications/aoj/intersection',
    'verifications/aoj/is_convex',
    'verifications/aoj/matrix_multiplication',
    'verifications/aoj/maximum_flow',
    'verifications/aoj/minimum_cost_flow',
    'verifications/aoj/parallel_orthogonal',
    'verifications/aoj/polygon_point_containment',
    'verifications/aoj/projection',
    'verifications/aoj/reflection',
    'verifications/aoj/single_source_shortest_path',
    'verifications/aoj/tangent_to_a_circle',
    'verifications/aoj/the_maximum_number_of_overlaps',
    'verifications/library_checker/bitwise_xor_convolution',
    'verifications/library_checker/convolution',
    'verifications/library_checker/enumerate_palindromes',
    'verifications/library_checker/factorize',
    'verifications/library_checker/line_add_get_min',
    'verifications/library_checker/primality_test',
    'verifications/library_checker/number_of_substrings',
    'verifications/library_checker/range_kth_smallest',
    'verifications/library_checker/rmq_disjoint_sparse_table',
    'verifications/library_checker/rmq_lazy_segment_tree',
    'verifications/library_checker/rmq_segment_tree',
    'verifications/library_checker/rmq_sparse_table',
    'verifications/library_checker/segment_add_get_min',
    'verifications/library_checker/shortest_path',
    'verifications/library_checker/static_range_frequency_wavelet_matrix',
    'verifications/library_checker/static_range_frequency',
    'verifications/library_checker/strongly_connected_components',
    'verifications/library_checker/suffix_array',
    'verifications/library_checker/sum_of_floor_of_linear',
    'verifications/library_checker/vertex_add_path_sum',
    'verifications/library_checker/vertex_add_path_sum2',
    'verifications/library_checker/vertex_add_subtree_sum',
    'verifications/library_checker/z_algorithm',
]

[profile.release]
lto = true
panic = 'abort'
overflow-checks = true

[profile.test]
opt-level = 3
