[config]
skip_core_tasks = true
default_to_workspace = false

[env]
VERIFY_DIR = ".competitive-verifier"
VERIFY_FILE = "verify.json"
VERIFY_RESULT_FILE = "result.json"
RUST_MIN_STACK = 104857600

[tasks.format]
description = "Reformat files"
install_crate = "rustfmt"
category = "Development"
command = "cargo"
args = ["fmt"]

[tasks.lint]
description = "Lint project files"
install_crate = "clippy"
category = "Development"
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.check]
description = "Check compile for Rust 1.70.0"
toolchain = "1.70.0"
category = "Development"
command = "cargo"
args = ["check"]

[tasks.test]
description = "Run unit tests"
category = "Development"
command = "cargo"
args = ["test"]

[tasks.coverage]
description = "Run unit tests with coverage"
toolchain = "nightly"
command = "cargo"
category = "Coverage"
args = ["llvm-cov", "--lcov", "--output-path", "lcov.info"]

[tasks.build]
dependencies = ["format", "lint", "check", "coverage", "verify", "snippet"]

[tasks.rustdoc]
env = { RUSTDOCFLAGS = "--html-in-header katex.html -Z unstable-options --generate-link-to-definition" }
description = "Generate rustdoc with KATEX"
command = "cargo"
toolchain = "nightly"
category = "Documentation"
args = [
	"doc",
	"--no-deps",
	"-Zunstable-options",
	"-Zrustdoc-scrape-examples",
	"--features",
	"verify_result",
]

[tasks.refresh-dropbox-token]
description = "Refresh local dropbox token"
category = "Verification"
script = '''
	curl https://api.dropbox.com/oauth2/token \
		-d grant_type=refresh_token \
		-d refresh_token=${DROPBOX_REFRESH_TOKEN} \
		-u ${DROPBOX_APP_KEY}:${DROPBOX_APP_SECRET} | \
		python3 -c "import sys, json; data=json.load(sys.stdin); print(data['access_token'], end='')" > dropbox_token
'''

[tasks.verify-download]
env = { PYTHON = "python3" }
description = "download verification problems"
category = "Verification"
script = '''
cargo test --release --features fetch_testcases --package library_checker_solvers -- --ignored
cargo test --release --features fetch_testcases --package yukicoder_solvers -- --ignored --test-threads=1
cargo test --release --features fetch_testcases --package atcoder_solvers -- --ignored --test-threads=1
cargo test --release --features fetch_testcases --package aizu_online_judge_solvers -- --ignored --test-threads=1
'''

[tasks.verify]
description = "verify problems"
command = "cargo"
category = "Verification"
args = ["test", "--release", "--lib", "--features", "verify", "--", "--ignored"]

[tasks.verify-run]
dependencies = ["verify-download", "verify"]

[tasks.verify-list]
command = "cargo"
category = "Verification"
args = [
	"test",
	"--release",
	"--lib",
	"--features",
	"verify",
	"--quiet",
	"--",
	"--list",
	"--ignored",
]

[tasks.snippet]
dependencies = ["codesnip-verify", "codesnip-cache"]

[tasks.codesnip-cache]
script = '''
    cargo codesnip --target=crates/rust_lib_for_comp/lib.rs --cfg=nightly cache target/codesnip/codesnip-cache.bin
'''

[tasks.codesnip-verify]
script = '''
	cargo codesnip --target=crates/rust_lib_for_comp/lib.rs --filter-item=test --cfg=nightly verify --verbose --toolchain=1.70.0 --edition=2021
'''

[tasks.codesnip-list]
script = '''
	cargo codesnip --target=crates/rust_lib_for_comp/lib.rs --cfg=nightly list
'''

[tasks.codesnip-bundle]
script = '''
	cargo codesnip --target=crates/rust_lib_for_comp/lib.rs --cfg=nightly bundle ${@}
'''
