[package]
name = "aoj_solver_parallel_orthogonal"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

plane_float = { path = "../../../crates/geometry/plane_float" }

[[bin]]
name = "parallel_orthogonal"
path = "main.rs"
