[package]
name = "atcoder_solver_abc141f"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

bit_matrix = { path = "../../../crates/data_structure/bit_matrix" }

[[bin]]
name = "atcoder_solver_abc141f"
path = "main.rs"
