[package]
name = "weighted_union_find"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
algebra = { path = "../../algebra" }

[dev-dependencies]
addition = { path = "../../algebra/binary_operation/addition" }

[lib]
path = "lib.rs"
