[package]
name = "io_debug"
version = "0.1.0"
edition = "2018"

[dependencies]
algebra = { path = "../../algebra" }
prelude = { path = "../../prelude" }
io_util = { path = "../io_util" }

[dev-dependencies]
string_util = { path = "../string_util" }

[lib]
path = "lib.rs"