[package]
name = "embedded_mod_factorial"
version = "0.1.0"
edition = "2018"

[dependencies]
mod_int = { path = "../" }
prelude = { path = "../../../prelude" }

[dev-dependencies]
string_util = { path = "../../../util/string_util" }

[lib]
path = "lib.rs"
