[package]
name = "library_checker_solver_rmq_cartesian_tree"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

cartesian_tree = { path = "../../../crates/graph/tree/cartesian_tree" }
lowest_common_ancestor = { path = "../../../crates/graph/tree/lowest_common_ancestor" }

[[bin]]
name = "library_checker_solver_rmq_cartesian_tree"
path = "main.rs"
