[package]
name = "yukicoder_bernoulli_bernoulli"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

lagrange_interpolation = { path = "../../../crates/algebra/lagrange_interpolation" }
mod_int = { path = "../../../crates/algebra/mod_int" }
const_mod_factorial = { path = "../../../crates/algebra/mod_int/const_mod_factorial" }

[[bin]]
name = "yukicoder_bernoulli_bernoulli"
path = "main.rs"
