[package]
name = "longest_common_prefix_array"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
suffix_array = { path = "../suffix_array" }

[lib]
path = "lib.rs"
