[package]
name = "adjacency_list"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
graph = { path = "../../graph" }

[dev-dependencies]
xor_shift = { path = "../../algo/xor_shift" }

[lib]
path = "lib.rs"