[package]
name = "lagrange_interpolation"
version = "0.1.0"
edition = "2018"

[dependencies]
algebra = { path = "../../algebra" }
mod_int = { path = "../../algebra/mod_int" }
prelude = { path = "../../prelude" }

const_mod_factorial = { path = "../mod_int/const_mod_factorial" }

[lib]
path = "lib.rs"
