[package]
name = "library_checker_solver_double_ended_prority_queue_w_ary_tree"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

complete_64_part_tree = { path = "../../../crates/data_structure/complete_64_part_tree" }
compress = { path = "../../../crates/algo/compress" }

[[bin]]
name = "library_checker_solver_double_ended_prority_queue_w_ary_tree"
path = "main.rs"
