[package]
name = "dynamic_union_find"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
fxhasher = { path = "../../algo/fxhasher" }
union_find = { path = "../union_find" }

[lib]
path = "lib.rs"
