[package]
name = "library_checker_solver_persistent_queue"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

persistent_queue = { path = "../../../crates/data_structure/persistent_queue" }

[[bin]]
name = "library_checker_solver_persistent_queue"
path = "main.rs"
