[package]
name = "convex_hull"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
min_max_macro = { path = "../../util/min_max_macro" }
plane_float = { path = "../plane_float" }
float_value = { path = "../../element/float_value" }

[lib]
path = "lib.rs"
