[package]
name = "succinct_indexable_dictionaries"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
string_util = { path = "../../util/string_util" }

[lib]
path = "lib.rs"
