[package]
name = "dynamic_li_chao_tree"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
min_max_macro = { path = "../../util/min_max_macro" }
range_traits = { path = "../../range_traits" }

[dev-dependencies]
xor_shift = { path = "../../algo/xor_shift" }

[lib]
path = "lib.rs"
