[package]
name = "heavy_light_decomposition"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../../prelude" }
graph = { path = "../../../graph" }
range_traits = { path = "../../../range_traits" }
algebra = { path = "../../../algebra" }
segment_tree = { path = "../../../data_structure/segment_tree" }

[dev-dependencies]
adjacency_list = { path = "../../adjacency_list" }
addition = { path = "../../../algebra/binary_operation/addition" }
sequence = { path = "../../../element/sequence" }
xor_shift = { path = "../../../algo/xor_shift" }

[lib]
path = "lib.rs"
