[package]
name = "heavy_light_decomposition"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../../prelude" }
graph = { path = "../../../graph" }
range_traits = { path = "../../../range_traits" }
algebra = { path = "../../../algebra" }

[dev-dependencies]
adjacency_list = { path = "../../adjacency_list" }
string_util = { path = "../../../util/string_util" }
io_util = { path = "../../../util/io_util" }
binary_indexed_tree = { path = "../../../data_structure/binary_indexed_tree" }
segment_tree = { path = "../../../data_structure/segment_tree" }
addition = { path = "../../../algebra/binary_operation/addition" }
sequence = { path = "../../../element/sequence" }

[lib]
path = "lib.rs"

[[example]]
name = "vertex_add_path_sum"
path = "./vertex_add_path_sum.rs"

[[example]]
name = "vertex_add_path_sum2"
path = "./vertex_add_path_sum2.rs"