[package]
name = "formal_power_series"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
algebra = { path = "../" }
mod_int = { path = "../mod_int" }

[lib]
path = "lib.rs"
