[package]
name = "library_checker_solver_factorize"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

pollard_rho = { path = "../../../crates/algebra/pollard_rho" }

[[bin]]
name = "library_checker_solver_factorize"
path = "main.rs"
