[package]
name = "aoj_solver_all_pairs_shortest_path"
version = "0.1.0"
edition = "2018"

[dependencies]
competitive = { path = "../../../" }

[[bin]]
name = "aoj_solver_all_pairs_shortest_path"
path = "main.rs"
