[package]
name = "baby_step_giant_step"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
sqrt = { path = "../../algo/sqrt" }
fxhasher = { path = "../../algo/fxhasher" }

[dev-dependencies]
mod_pow = { path = "../../algebra/mod_pow" }

[lib]
path = "lib.rs"