[package]
name = "greatest_common_divisor"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../../prelude" }
algebra = { path = "../../" }

[dev-dependencies]
criterion = "0.5.1"
xor_shift = { path = "../../../algo/xor_shift" }

[lib]
path = "lib.rs"

[[bench]]
name = "binary-gcd"
path = "./bench_binary_gcd.rs"
harness = false
