[package]
name = "library_checker_solver_primality_test"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

miller_rabin = { path = "../../../crates/algebra/miller_rabin" }

[[bin]]
name = "library_checker_solver_primality_test"
path = "main.rs"
