[package]
name = "prim"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
graph = { path = "../../graph" }
algebra = { path = "../../algebra" }
union_find = { path = "../../data_structure/union_find" }

[dev-dependencies]
adjacency_matrix = { path = "../../graph/adjacency_matrix" }

[lib]
path = "lib.rs"