[package]
name = "library_checker_solver_rmq_lazy_segment_tree"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

algebra = { path = "../../../crates/algebra" }
range_traits = { path = "../../../crates/range_traits" }
minimization = { path = "../../../crates/algebra/binary_operation/minimization" }
lazy_segment_tree = { path = "../../../crates/data_structure/lazy_segment_tree" }

[[bin]]
name = "library_checker_solver_rmq_lazy_segment_tree"
path = "main.rs"
