[package]
name = "matrix"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
algebra = { path = "../../algebra" }

[dev-dependencies]
mod_int = {path = "../../algebra/mod_int" }

[lib]
path = "lib.rs"

