[package]
name = "atcoder_solver_abc226f"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

algebra = { path = "../../../crates/algebra" }
mod_int = { path = "../../../crates/algebra/mod_int" }
const_mod_val_table = { path = "../../../crates/algebra/const_mod_val_table" }
split_of_natural_number = { path = "../../../crates/enumerator/split_of_natural_number" }
greatest_common_divisor = { path = "../../../crates/algebra/binary_operation/greatest_common_divisor" }

[[bin]]
name = "atcoder_solver_abc226f"
path = "main.rs"
