[package]
name = "library_checker_solver_point_set_range_composite"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

range_traits = { path = "../../../crates/range_traits" }
segment_tree = { path = "../../../crates/data_structure/segment_tree" }
affine = { path = "../../../crates/element/affine" }
mod_int = { path = "../../../crates/algebra/mod_int" }

[[bin]]
name = "library_checker_solver_point_set_range_composite"
path = "main.rs"
