[package]
name = "pollard_rho"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
montgomery_multiplication_64 = { path = "../../algebra/montgomery_multiplication_64" }
greatest_common_divisor = { path = "../../algebra/binary_operation/greatest_common_divisor" }
miller_rabin = { path = "../../algebra/miller_rabin" }
algebra = { path = "../../algebra" }

[lib]
path = "lib.rs"