[package]
name = "miller-rabin"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
montgomery_multiplication_64 = { path = "../../algebra/montgomery_multiplication_64" }
algebra = { path = "../../algebra" }

[lib]
path = "lib.rs"