[package]
name = "retrograde_analysis"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
graph = { path = "../../graph" }
adjacency_list = { path = "../../graph/adjacency_list" }

[lib]
path = "lib.rs"