[package]
name = "library_checker_solver_set_xor_min"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

binary_trie = { path = "../../../crates/data_structure/binary_trie" }

[[bin]]
name = "library_checker_solver_set_xor_min"
path = "main.rs"
