[package]
name = "library_checker_solver_matrix_product"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }
prelude = { path = "../../../crates/prelude" }

matrix = { path = "../../../crates/algebra/matrix" }
mod_int = { path = "../../../crates/algebra/mod_int" }

[[bin]]
name = "library_checker_solver_matrix_product"
path = "main.rs"
