[package]
name = "verify_attr"
version = "0.1.0"
authors = ["to-omer <toomerhs@gmail.com>"]
edition = "2021"

[lib]
doc = false
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
