[package]
name = "library_checker_solver_point_add_range_sum"
version = "0.1.0"
edition = "2018"

[dependencies]
io_util = { path = "../../../crates/util/io_util" }
io_debug = { path = "../../../crates/util/io_debug" }
string_util = { path = "../../../crates/util/string_util" }

range_traits = { path = "../../../crates/range_traits" }
addition = { path = "../../../crates/algebra/binary_operation/addition" }
binary_indexed_tree = { path = "../../../crates/data_structure/binary_indexed_tree" }

[[bin]]
name = "library_checker_solver_point_add_range_sum"
path = "main.rs"
