[package]
name = "warshall_floyd"
version = "0.1.0"
edition = "2018"

[dependencies]
prelude = { path = "../../prelude" }
graph = { path = "../../graph" }
algebra = { path = "../../algebra" }

[dev-dependencies]
adjacency_list = { path = "../../graph/adjacency_list" }

[lib]
path = "lib.rs"