name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: --html-in-header katex.html

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            library/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          working-directory: ./library
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
          working-directory: ./library
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
          working-directory: ./library
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps
          working-directory: ./library
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./library/target/doc/
