name: Rust

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: --html-in-header /home/runner/work/rust_lib_for_comp/rust_lib_for_comp/katex.html

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0 # for inclimental build: ファイルがcommitされた時刻を取得する

      - uses: actions/setup-python@v1

      - uses: actions/cache@v2
        with:
          path: |
            ~/.vendor/bundle
            ~/.cache/pip
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            .verify-helper/
          key: always

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
  
      - run: pip3 install -U online-judge-verify-helper

      - name: Install Rust
        run: |
          rustup install 1.70.0
          rustup default nightly
          rustup set profile minimal
          rustup component add clippy
      
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "lib"

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - name: Lint
        run: cargo clippy --workspace -- -D warnings

      - name: Compile
        run: cargo +1.70.0 check     

      - name: Verify problems
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: oj-verify run -j 32
      
      - name: Generate code coverage
        run: cargo +nightly llvm-cov --workspace --doctests --ignore-filename-regex .*verifications\/.* --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true

      - name: Generate docs
        run: |
          oj-verify docs
          cd .verify-helper/markdown
          bundle config set --local path '.vendor/bundle'
          bundle install
          bundle exec jekyll build
          cd ../../
          mkdir public
          cp -frP .verify-helper/markdown/_site/* public/
          cargo doc --workspace --no-deps
          cp -rP target/doc/* public/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: library.katand.net
