name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cd library && cargo test --verbose

  doc:
    runs-on: ubuntu-latest
    needs: test
    if:  github.event_name == 'push' || github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2
      - name: Run doc
        run: cd library && cargo doc --no-deps --document-private-items

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./library/target/doc/
