name: Rust

on: push

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: --html-in-header /home/runner/work/rust_lib_for_comp/rust_lib_for_comp/katex.html

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/rust.yml') }}

      - uses: actions/setup-python@v1
      - run: pip3 install -U online-judge-verify-helper

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.42.0-x86_64-unknown-linux-gnu
          default: true
          profile: minimal
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.42.0-x86_64-unknown-linux-gnu
          default: false
          profile: minimal
      - run: rustup component add clippy

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run:
        cargo +1.42.0 check
        cargo +1.65.0 clippy --workspace -- -D warnings
        cargo +1.65.0 test --workspace
        oj-verify run -j 32

    - name: Generate docs
      run:
        oj-verify docs
        cargo +1.65.0 doc --workspace --no-deps
        mv .verify-helper/markdown/* target/doc

    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/
